### ISSUE TITLE
publish latest version

### ISSUE THREAD

**Issue by xmlking** [thake/avro4k-kafka-serializer#11]
can you publish latest version. 1.3.0 was from 2020

**Comment by thake** [comment]
@xmlking I will publish a new version in the first week of 2022. I won't have any time before that.

**Comment by e-kosten** [comment]
@thake this project looks really great but I'm getting some dependency conflicts which I suspect would be fixed by the latest commits. Do you still expect to push a new version?

**Comment by thake** [comment]
I've updated the dependencies in the master branch. Does this work for you? If so I'll craft a release.

**Comment by thake** [comment]
I've just pushed a new version. It should be available soon on maven central.

@xmlking, thank you for your great PR! Sorry that it took me so long to integrate it and push a new version. I just forgot about it.

**Comment by e-kosten** [comment]
I pulled this locally, built the jar and discovered two things:
- When building the jar locally and importing it into my project, I was getting some ClassNotFound exceptions until I manually added `com.github.michaelbull.retry` to my classpath. Not a big issue but I wonder why this is not included in the bundle?
- While evaluating the master version I realized that my actual issue was coming from another dependency which was using a really old version of the `kafka-avro-serializer` library. After removing that both versions 0.13.0 and the latest version 0.14.0 that you just pushed seem to work

**Comment by thake** [comment]
> When building the jar locally and importing it into my project, I was getting some ClassNotFound exceptions until I manually added com.github.michaelbull.retry to my classpath. Not a big issue but I wonder why this is not included in the bundle?

Generally speaking, the jar does not contain any external dependency. This should be handled by your preferred build tool (maven, gradle,...) through transitive dependency management. 
I've just created an example project using gradle with the latest 0.14.0 version without needing to specify com.github.michaelbull.retry as an explicit dependency. You can have a look at it: https://github.com/thake/avro4k-kafka-serializer-example
